### ISSUE TITLE
Leaflet 0.7.5 Compatibility

### ISSUE THREAD

**Issue by hellracer** [oskosk/Leaflet.Weather#1]
Hi Author,

This is really a cool plugin for leaflet, do you think it's compatible with leaft v0.7.5? I try various permutation but I can't seems to get it to work.

I carefully follow the instruction on the sample code but I can't get it to work on firebug I don't see any JS error or something.

Thanks

**Comment by oskosk** [comment]
Hi! I think therr maybe somethon new. in 0.7.5 let me check that. I'll come
back in a moment

**Comment by hellracer** [comment]
Hi Osk,

Thanks much appreciate it.

---

On Thu, 9/24/15, Osk notifications@github.com wrote:

 Subject: Re: [Leaflet.Weather] Leaflet 0.7.5 Compatibility (#1)
 To: "oskosk/Leaflet.Weather" Leaflet.Weather@noreply.github.com
 Cc: "hellracer" loloski@yahoo.com
 Date: Thursday, September 24, 2015, 10:52 PM

 Hi! I think therr maybe somethon
 new. in 0.7.5 let me check that. I'll come

 back in a moment

 On Thu, Sep 24, 2015, 10:05 AM hellracer
 notifications@github.com wrote:

> Hi Author,
> 
> This is really a cool plugin for leaflet, do you think
>  it's compatible
> 
> with leaft v0.7.5? I try various permutation but I
>  can't seems to get it to
> 
> work.
> 
> I carefully follow the instruction on the sample code
>  but I can't get it
> 
> to work on firebug I don't see any JS error or
>  something.
> 
> Thanks
> 
> —
> 
> Reply to this email directly or view it on GitHub
> 
>  https://github.com/oskosk/Leaflet.Weather/issues/1.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by hellracer** [comment]
Hi, by any chance would you be able to check? thank in adavnce

**Comment by oskosk** [comment]
Hey @hellracer . Sorry for the delay. Look http://jsbin.com/ceqovosegu/edit?html

There's an example of the plugin working with 0.7.5. I see no issue there. Can you confirm ?

**Comment by hellracer** [comment]
Hi Author,

Thanks for looking into this, please close this now. I can concur that it is a user problem :)

Best regards,

Ronald Chan

---

On Sun, 9/27/15, Osk notifications@github.com wrote:

 Subject: Re: [Leaflet.Weather] Leaflet 0.7.5 Compatibility (#1)
 To: "oskosk/Leaflet.Weather" Leaflet.Weather@noreply.github.com
 Cc: "hellracer" loloski@yahoo.com
 Date: Sunday, September 27, 2015, 10:32 PM

 Hey @hellracer . Sorry for
 the delay. Look http://jsbin.com/ceqovosegu/edit?html

 There's an example of the plugin working with 0.7.5.
 I see no issue there. Can you confirm ?

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by hellracer** [comment]
Hi Author,
by the way I think the value returned by the API by default for the temperature is in degrees kelvin?

tpl = tpl.replace(":temperature", Math.round(parseFloat(weather.main.temp-273)).toFixed(1)); // Kelvin to Degrees Celcius
tpl = tpl.replace(":temperature", Math.round(parseFloat((weather.main.temp*1.8)-459.67)).toFixed(2)); // Kelvin to Degrees Fahrenhei

Just my 0.2
Best
Ronald Chan

```
 On Sunday, September 27, 2015 10:51 PM, Ronald Chan <loloski@yahoo.com> wrote:
```

 Hi Author,

Thanks for looking into this, please close this now. I can concur that it is a user problem :)

Best regards,

Ronald Chan

---

On Sun, 9/27/15, Osk notifications@github.com wrote:

 Subject: Re: [Leaflet.Weather] Leaflet 0.7.5 Compatibility (#1)
 To: "oskosk/Leaflet.Weather" Leaflet.Weather@noreply.github.com
 Cc: "hellracer" loloski@yahoo.com
 Date: Sunday, September 27, 2015, 10:32 PM

 Hey @hellracer . Sorry for
 the delay. Look http://jsbin.com/ceqovosegu/edit?html

 There's an example of the plugin working with 0.7.5.
 I see no issue there. Can you confirm ?

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by oskosk** [comment]
great thanks. I'll update the docs to reflect that
