### ISSUE TITLE
Demo does not work

### ISSUE THREAD

**Issue by felipinbombin** [oskosk/Leaflet.Weather#6]
Hi! 
as the title says, the demo throw an error when Leaflet.weather is loaded

**Comment by oskosk** [comment]
Thanks for the report. I just fixed that error.

Still, as mentioned in the README, this remains true:

> OpenWeatherMap API now requires you to get an API Key. So this plugin is no longer working. I'm working on an update to enable OpenWeatherMap API keys for this plugin

I haven't find any time yet to cope with this new behaviour.
