### ISSUE TITLE
I have got an API key from openweathermap

### ISSUE THREAD

**Issue by sydgis** [oskosk/Leaflet.Weather#9]
Is there is any way to use an API key to add that widget using this good plugin?

**Comment by kitesaint1309** [comment]
I edited the Leaflet.Weather.js file on line 37: `url = "http://api.openweathermap.org/data/2.5/weather?APPID={appId}&lat=:lat&lon=:lng&lang=:lang&units=:units";` you should replace {appId} with your API key, this gave me a working version. But I didn't use it any further as I required more data to be shown.
Hope this helps

**Comment by lefcgis** [comment]
Definitely, this is the key to use it 👆

Thanks! 💪

**Comment by oskosk** [comment]
Fixed in #12
